# language: node_js
# node_js:
#   - 'node'
# services:
#   - docker
# jobs:
#   include:
#     - stage: test
#       script:
#         - npm install
#         - npm test
#     - stage: docker-deploy-image
#       script:
#         - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
#         - docker build -t andrewbestbier/ci-comparison-blog .
#         - docker push andrewbestbier/ci-comparison-blog
#     - stage: deploy
#       script: skip
#       deploy:
#         provider: elasticbeanstalk
#         access_key_id: $AWS_ACCESS_KEY_ID
#         secret_access_key: $AWS_SECRET_ACCESS_KEY
#         region: 'eu-west-2'
#         app: 'CI Comparison Blog'
#         env: 'CiComparisonBlog-env'
#         bucket_name: 'elasticbeanstalk-eu-west-2-094505317841'
#         bucket_path: 'CI Comparison Blog'

language: node_js # (1)
node_js:
  - 'node'
services:
  - docker # (2)
jobs:
  include:
    - stage: test
      script:
        - npm install # (3)
        - npm test # (4)
    - stage: docker-deploy-image # (5)
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t vanthedev/ci-comparison-blog .
        - docker push vanthedev/ci-comparison-blog
    - stage: deploy
      script: skip
      deploy: # (6)
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: 'us-east-2'
        app: 'CI Comparison Blog'
        env: 'CiComparisonBlog-env'
        bucket_name: 'Cicomparisonblog-env.eba-2mmnybnx.us-east-2.elasticbeanstalk.com'
        bucket_path: 'CI Comparison Blog'
